replicaCount: 1
useVersionSidecar: true

image:
  pullPolicy: IfNotPresent
  spec: nginx:alpine

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: test.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: test-tls-secret
      hosts:
        - test.com

resources:
  limits:
    cpu: 500m
    memory: 2048Mi
  requests:
    cpu: 200m
    memory: 1024Mi

cronJobs:
  e2e-run:
    schedule: "0 * * * *"
    restartPolicy: "Never"
    imagePullPolicy: "IfNotPresent"
    command: ["/bin/sh", "-c", "echo e2e-ok"]
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 256Mi
