{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: {{ include "app.fullname" . }}
    kind: SecretStore
  target:
    name: "{{ .Values.externalSecrets.secretName}}"
  dataFrom:
  - extract:
      key: "{{ .Values.externalSecrets.extractKey}}"
{{- end }}
