{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  provider:
    vault:
      server: "{{ .Values.externalSecrets.provider.serverAddress}}"
      path: "{{ .Values.externalSecrets.provider.secretPath }}"
      version: "v2"
      namespace: "{{ .Values.externalSecrets.provider.namespace }}"
      auth:
        appRole:
          path: "approle"
          roleRef:
            name: "{{ .Values.externalSecrets.provider.appRole.secretName }}"
            key: "{{ .Values.externalSecrets.provider.appRole.roleIdKey }}"
          secretRef:
            name: "{{ .Values.externalSecrets.provider.appRole.secretName }}"
            key: "{{ .Values.externalSecrets.provider.appRole.roleSecretKey }}"
{{- end }}
