name: Tests

on:
  pull_request:
  push:

jobs:
  run-tests:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: azure/setup-helm@v4
      - name: Install helm unittest plugin
        run: helm plugin install https://github.com/helm-unittest/helm-unittest
      - name: Run helm unittest
        run: helm unittest charts/app
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      # - uses: helm/kind-action@v1
      # - run: |
      #     curl -sSL https://git.io/chart-testing | bash
      #     ct lint --charts charts/app
      #     ct install --charts charts/app
      # - run: kubectl wait --for=condition=ready pod -l app.kubernetes.io/instance=app --timeout=120s
