name: Tests and linting

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  run-tests:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Setup KinD
        uses: helm/kind-action@v1
        with:
          cluster_name: ct

      - name: Setup chart-testing
        uses: helm/chart-testing-action@v2

      - name: Install kubeconform
        run: |
          curl -sSL https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz \
          | tar xz
          sudo mv kubeconform /usr/local/bin/

      - name: Install kube-linter
        run: |
          curl -sSL https://github.com/stackrox/kube-linter/releases/latest/download/kube-linter-linux.tar.gz \
          | tar xz
          sudo mv kube-linter /usr/local/bin/

      # Unit tests for template logic
      - name: Install helm unittest plugin
        run: helm plugin install https://github.com/helm-unittest/helm-unittest
      - name: Run helm unittest
        run: helm unittest charts/app 

      # Static lint of the chart
      - name: Lint charts
        run: ct lint --charts charts/app --helm-extra-args "--strict" 

      - name: Render Helm
        run: |
          helm template app charts/app -f charts/app/ci/ci-values.yaml > rendered.yaml

      - name: kubeconform
        run: kubeconform -summary -strict -ignore-missing-schemas < rendered.yaml

      - name: kube-linter
        run: kube-linter lint rendered.yaml
        continue-on-error: true # For now we want to continue even if it fails, first we have to clean up helms that use this as dependency
        
      # Install chart into a throwaway ns and wait for readiness (proves it deploys)
      - name: Install charts (ct)
        run: ct install --charts charts/app

      # Integration smoke: install into fixed ns with CI values
      - name: Install for CronJob smoke (fixed ns)
        run: |
          helm upgrade --install app charts/app -n e2e --create-namespace \
            -f charts/app/ci/ci-values.yaml --wait --timeout 5m0s
      - name: Trigger CronJob once and verify
        run: |
          NS=e2e
          CJ=$(kubectl -n "$NS" get cronjob -l app.kubernetes.io/instance=app \
               -o jsonpath='{.items[0].metadata.name}')
          echo "CronJob: $CJ"
          kubectl -n "$NS" create job --from=cronjob/$CJ smoke
          kubectl -n "$NS" wait job/smoke --for=condition=complete --timeout=180s
          kubectl -n "$NS" logs job/smoke
